name: Build & Deploy Jekyll

on:
  push:
    branches:
      - main

permissions:
  contents: write       # ensure the GITHUB_TOKEN can push commits
  pages: write          # allow Pages deployment
  id-token: write       # needed by peaceiris/actions-gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true   # critical so github-actions[bot] can push

      - name: Set up Ruby 3.1
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install Bundler & dependencies
        run: |
          gem install bundler       # installs the latest Bundler (2.6.x on Ruby 3.1)
          bundle install            # pulls in Jekyll, your theme, plugins, etc.

      - name: Build Jekyll _site
        run: bundle exec jekyll build --destination ./_site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
